### Author: Mirco Migliavacca, Ulisse Gomarasca
labelGPPsat <- expression(paste("GPPsat [", mu,mol,CO[2]," ", m^{-2},s^{-1},"]"))
labelRb <- expression(paste("Rb [", mu,mol,CO[2]," ", m^{-2},s^{-1},"]"))
labelNmass <- expression(paste("N% [gN 100", g[leaf]^{-1},"]"))
labelG1 <- expression(paste("G1 [",kPa^{0.5},"]"))
labelGs <- expression(paste("Gs [",m," ", s^{-1},"]"))
labelGsmax <- expression(paste("Gsmax [",m," ", s^{-1},"]"))
labelWUE <- expression(paste("WUE [",gC," ", kgH[2],O,"]"))
labelWUE_NEE <- expression(paste("WUEn [",gC," ", kgH[2],O^{-1},"]"))
# labelIWUE <- expression(paste("IWUE [",gC," ",kPa," ", kgH[2],O^{-1},"]"))
labeluWUE <- expression(paste("uWUE [",gC," ",kPa^{0.5}," ", kgH[2],O^{-1},"]"))
labelWUEt <- expression(paste("WUEt [",gC," ", kgH[2],O^{-1},"]"))
labeluWUEt <- expression(paste("uWUEt [",gC," ", kPa^{0.5}, kgH[2],O^{-1},"]"))
labelLAImax <- expression(paste("LAImax [",m^{2}," ", m^{-2},"]"))
labelEF <- expression(paste("EF [-]"))
labelCSWI <- expression(paste("CSWI [-]"))
labelPrecip <- expression(paste("P [mm]"))
# labelAge <- expression(paste("Age [yrs]"))
# labellnAge <- expression(paste("ln(Age) [yrs]"))
labelTa <- expression(paste("Tair [",degree, "C]"))
# labelPrecip_mm <- expression(paste("P [mm"," ", month^{-1},"]"))
labelSW_IN <- expression(paste("SW_IN [W ", m^{-2},"]"))
# labelLAIN <- expression(paste("LAImax x N% [",m^{2}," ", m^{-2}," gN 100", g[leaf]^{-1},"]"))
# labelHLE <- expression(paste("H + LE [W ", m^{-2},"]"))
# labelRn_G <- expression(paste("NetRad - G [W ", m^{-2},"]"))
labelVPD <- expression(paste("VPD [hPa]"))
# labelmax_hc <- expression(paste("Hc [m]"))
# labelAGB <- expression(paste("AGB [t DM ", ha^{-1},"]"))
# labelFO2ASFMHyPlant <- expression(paste("F",O[2],"A", "HyPlant SFM", "[mW ", m^{-2}, nm^{-1},sr^{-1},"]"))
# labelFO2BSFMHyPlant <- expression(paste("F",O[2],"B", "HyPlant SFM", "[mW ", m^{-2}, nm^{-1},sr^{-1},"]"))
# labelFO2BSFMFLOX <- expression(paste("F",O[2],"B", "FLoX SFM", "[mW ", m^{-2}, nm^{-1},sr^{-1},"]"))
# labelFO2ASFMFLOX <- expression(paste("F",O[2],"A", "FLoX SFM", "[mW ", m^{-2}, nm^{-1},sr^{-1},"]"))
# labelFO2AiFLDHyPlant <- expression(paste("F",O[2],"A", "HyPlant iFLD", "[mW ", m^{-2}, nm^{-1},sr^{-1},"]"))
# labelFO2BiFLDHyPlant <- expression(paste("F",O[2],"B", "HyPlant iFLD", "[mW ", m^{-2}, nm^{-1},sr^{-1},"]"))
# labelFO2BiFLDFLOX <- expression(paste("F",O[2],"B", "FLoX iFLD", "[mW ", m^{-2}, nm^{-1},sr^{-1},"]"))
# labelFO2AiFLDFLOX <- expression(paste("F",O[2],"A", "FLoX iFLD", "[mW ", m^{-2}, nm^{-1},sr^{-1},"]"))

labelLL <- expression(paste("Leaf Longevity (LL) [month]"))
labelwLL <- expression(paste("Weighted Leaf Longevity (wLL) [month]"))
labelSLA <- expression(paste("Specific Leaf Area (SLA) [", mm^{2}," ", mg^{-1},"]"))
labelLMA <- expression(paste("Leaf Mass per Area (LMA) [mg", " ", mm^{-2},"]"))
labelwLMA <- expression(paste("Weighted Leaf Mass per Area (LMA) [mg", " ", mm^{-2},"]"))
labelwNmass <- expression(paste("N% [gN 100", g[leaf]^{-1},"]"))
labelwNarea <- expression(paste("Narea [gN ", m[leaf]^{-2},"]"))
labelSPPcover <- expression(paste("Species relative coverage [%]"))
labelAmass <- expression(paste("Photosynthesis rate (", Amax[mass], ") [", mu, mol, " ", g^{-1}, s^{-1}, "]"))
labelVcmax_mass <- expression(paste("Carboxylation capacity (", Vcmax[mass], ") [", n, mol, " ", g^{-1}, s^{-1}, "]"))
labelVcmax_area <- expression(paste("Carboxylation capacity (", Vcmax[area], ") [", mu, mol, " ", m^{-2}, s^{-1}, "]"))
labelRbmax <- expression(paste("Rbmax [", mu, mol,CO[2]," ", m^{-2},s^{-1},"]"))
labelcover <- expression(paste("Relative coverage [%]"))
labelPNUEmass <- expression(paste("PNUEmass[leaf] [", mu, mol, CO[2], g[leaf], m^{-2}, s^{-1}, gN^{-1},"]"))
labelPNUE <- expression(paste("PNUE [", mu, mol, CO[2], gN^{-1}, s^{-1},"]"))
labelAPAR_wNmass <- expression(paste("APAR / wNmass [", mu, mol, CO[2], g[leaf], m^{-2}, s^{-1}, gN^{-1},"]")) # CHECK UNITS
# labelPNUE_NEP <- expression(paste("PNUE from NEPmax [", mu, mol, CO[2], g[leaf], m^{-2}, s^{-1}, gN^{-1},"]"))
labelPNUEarea <- expression(paste("PNUEarea[leaf] [", mu, mol, CO[2], m^{2}[leaf], m^{-2}, s^{-1}, gN^{-1},"]"))
# labelPNUEarea_eco <- expression(paste("PNUEarea[ecosystem] [", mu, mol, CO[2], s^{-1}, gN^{-1},"]"))
# labelPNUEmean <- expression(paste("PNUE = fPAR x SW_IN / Nmass"))
# labelPNUEmax <- expression(paste("PNUE = fPAR x SW_IN / Nmass"))
# labelWUEt_50_mean <- expression(paste("Mean WUEt from TEA_T_NT_50 [",gC," ", kPa^{0.5}, kgH[2],O^{-1},"]"))
# labelWUEt_50_max <- expression(paste("95th quantile of WUEt from TEA_T_NT_50 [",gC," ", kPa^{0.5}, kgH[2],O^{-1},"]"))
labelWUEet <- expression(paste("WUE from evapotranspiration [",gC," ", kPa^{0.5}, kgH[2],O^{-1},"]"))
labelWUEtmax <- expression(paste("90th quantile of daily WUEt from TEA_T_NT_75 [",gC," ", kPa^{0.5}, kgH[2],O^{-1},"]"))
labelpWUEt <- expression(paste("peak WUEt from TEA_T_NT_75 [",gC," ", kPa^{0.5}, kgH[2],O^{-1},"]"))
labelelevation <- expression(paste("Elevation [m]"))
labelHc <- expression(paste("Canopy height [m]"))
labeln_spp <- expression(paste("Number of species"))
labelshannon <- expression(paste("Shannon-Weaver Index"))
labelevenness <- expression(paste("Pielou Evenness Index"))
labelwSSD <- expression(paste("Stem Specific Density [",g," ", cm^{-1},"]"))
labelwPSI50 <- expression(paste("Xylem water potential at which 50% of conductivity is lost [MPa]"))
# labelGsmax_old <- expression(paste("Gsmax [",m," ", s^{-1},"]"))
labelfPAR <- expression(paste("fPAR"))
labelAPAR <- expression(paste("APAR = fPAR x SW_IN"))
labelAPARmax <- expression(paste("Maximum APAR = fPAR x SW_IN"))
labelGPP_NT <- expression(paste("GPP_NT"))
labelLAInormGPPsat <- expression(paste("GPPsat / LAImax [", mu,mol,CO[2]," ", m^{-2},s^{-1},"]"))
labelLAIKnormGPPsat <- expression(paste("GPPsat / e^(-k * LAImax) [", mu,mol,CO[2]," ", m^{-2},s^{-1},"]"))
labelRECOmax <- expression(paste("Maximum night-time NEE (ecosystem respiration)"))